Objetivo 1 completado
paula1999/IV pull request #5
Opened 2021-09-27 16:24 UTC by paula1999

- Actualización del README.
- Documentación sobre las historias de usuario.
- Historias de usuario añadidas a las issues con su correspondiente etiqueta.
- Creación de milestones.

2021-09-27 17:03 UTC, JJ requested changes
Por favor, trata de comprender mejor el concepto de "producto mínimamente viable" y aplícalo a la descripción de los hitos. Al final, la pregunta es "¿Con esto, me puedo poner a programar?"

2021-09-29 06:33 UTC, JJ requested changes
Has llegado muy cerca de alcanzar el objetivo, sin embargo los MVPs ni son productos mínimamente viables ni están claramente organizados de forma lógica para empezar el desarrollo. Entre otras cosas, falta algún hito previo que contenga la lógica de negocio, por ejemplo. Sin la lógica de negocio implementada, no se va a obtener ningún beneficio de la aplicación.
Cuida también que los hitos estén descritos como MVPs.

2021-09-29 06:33 UTC, JJ commented on docs/historias_de_usuario.md
> +- **Gestor**. Es el encargado de obtener las tendencias entre los oyentes y realizar sugerencias con dicha información.
La lógica de negocio no puede estar creada por una persona. El "encargado" en todo caso, sería la lógica de negocio.

2021-09-29 06:33 UTC, JJ commented on docs/historias_de_usuario.md
> +- [HU1](https://github.com/paula1999/IV/issues/2). Como gestor, me gustaría realizar gráficas en las que pueda comparar las reproducciones de una misma canción distinguiendo las distintas localidades
Creo que has identificado claramente cuál es el beneficio de la aplicación.

2021-09-29 06:36 UTC, JJ commented
Fíjate que no has hecho ninguna HU del "melómano". Me vale, porque realmente al inicio el otro va a ser el que importe. Pero hay dos problemas: todos los usuarios deben obtener beneficios con la aplicación (si no, no la van a usar) y el gestor no va a tener ningún tipo de datos hasta que el melómano (muchos melómanos, de hecho) no se pongan a escuchar.

2021-09-29 09:56 UTC, paula1999 commented
He añadido algunos cambios, ya está listo para revisión.

2021-09-29 10:03 UTC, JJ reviewed
Por favor, Paula, trata de entender el concepto de producto mínimamente viable. El taller de esta tarde te puede ayudar. Un PMV nunca puede ser "funcionalidad", por ejemplo. Y también tienen que seguir un orden lógico. Los mojones están ordenados, y van uno después de otro. Aquí no está claro qué va después de qué.
Como siempre, imagina que esto se lo vamos a dar a otra persona para que desarrolle (cosa que es muy probable, por otro lado). ¿Cómo entiende esa persona lo que tiene que hacer?

2021-09-29 11:20 UTC, paula1999 commented
Ya he añadido la planificación a la documentación para aportar un orden lógico y también he organizado mejor los milestones.

2021-09-29 14:01 UTC, JJ commented
> Por favor, Paula, trata de entender el concepto de producto mínimamente viable. El taller de esta tarde te puede ayudar. Un PMV nunca puede ser "funcionalidad", por ejemplo.

Os agradecería que trabajárais todos los aspectos que os comento, y que lo pusiérais listo para revisión sólo cuando lo hagáis. Por otro lado, los milestones siguen sin estar ordenador ni tener un número. El documento puede ayudar a corregir, pero lo que hay en el repo es lo definitivo.

2021-09-29 16:15 UTC, paula1999 commented
He añadido la numeración de los milestones, diría que con eso ya quedarían bien ordenados. En cuanto a los PMV, no logro entender por qué no está bien. Me queda claro que no pueden ser "funcionalidad", he intentado expresarlo mejor pero no sé cómo arreglarlo.

2021-09-30 05:30 UTC, JJ commented
Por favor, revisa el taller de ayer sobre productos mínimamente viables, donde te explica qué lo es y como describirlo. Por otro lado, el "dado que" de las historias de usuario tiene que describir el contexto en el que se puede llevar a cabo esa acción. Por favor, consutla también qué es una HU y cámbialas en consecuencia.

2021-10-01 12:24 UTC, paula1999 commented
Listo para la revisión.

2021-10-02 06:43 UTC, JJ approved these changes
OK, quedamos que @olasergiolas tendría que hacer el siguiente objetivo, ¿no?

2021-10-02 09:35 UTC, paula1999 commented
Sí

2021-10-02 16:28 UTC, merged